version: '3'

services:
  nginx-proxy:
    image: nginx
    container_name: nimix
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./out/:/var/www/front/
